# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

environment:
  BASH_ENV: "~/.bashrc"

references:
  common_steps: &common_steps

    environment:
          BASH_ENV: "~/.bashrc"

    steps:

      - checkout

      - run:
          name: test command
          command: |
            pwd
            ls -lah
            ls -lah .circleci
            whereis curl
            ./.circleci/prepare_tests.sh

      # run tests!
      - run: npm test
      - run: CODECLIMATE_REPO_TOKEN=7af3b6e727d9048176742b35453561aab3b79ca0d3bccfba773bccf7fc9aa30e node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info

jobs:
  node4:
    docker:
      - image: node:4
    <<: [ *common_steps ]

  node5:
    docker:
      - image: node:5
    <<: [ *common_steps ]

  node6:
    docker:
      - image: node:6
    <<: [ *common_steps ]

  node7:
    docker:
      - image: node:7
    <<: [ *common_steps ]

  node8:
    docker:
      - image: node:8
    <<: [ *common_steps ]

workflows:
  version: 2
  build:
    # Evidently CircleCI can't cope with unique job
    # names unless workflows are used.
    jobs:
      - node4
      - node5
      - node6
      - node7
      - node8
