# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

environment:
  BASH_ENV: "~/.bashrc"

references:
  common_steps: &common_steps

    environment:
          BASH_ENV: "~/.bashrc"

    steps:

      - run:
          name: Installing binaries
          command: |
            apt-get update
            apt-get install tree

      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - restore_cache:
          key: cowlog-cache-{{ checksum "packages/cowlog/package.json" }}

      - run:
          name: Checking directroy tree
          command: |
            tree ./

      - run:
          name: prepare tests
          command: |
            pwd
            ./.circleci/prepare-tests.sh

      - run: npm run test

      - store_artifacts:
          path: coverage
          destination: prefix

      - store_test_results:
          path: coverage/lcov-report/

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - save_cache:
          key: cowlog-cache-{{ checksum "packages/cowlog/package.json" }}
          paths:
            - packages/cowlog/node_modules

      - run: CODECLIMATE_REPO_TOKEN=7af3b6e727d9048176742b35453561aab3b79ca0d3bccfba773bccf7fc9aa30e node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info

      - run:
          name: Document Update
          command: |
            pwd
            ./.circleci/document-updates.sh

jobs:
  node6:
    docker:
      - image: node:6
    <<: [ *common_steps ]

  node7:
    docker:
      - image: node:7
    <<: [ *common_steps ]

  node8:
    docker:
      - image: node:8
    <<: [ *common_steps ]

  node9:
    docker:
      - image: node:9
    <<: [ *common_steps ]

workflows:
  version: 2
  build:
    # Evidently CircleCI can't cope with unique job
    # names unless workflows are used.
    jobs:
      - node6
#      - node7
#      - node8
#      - node9
